In [6]:
import pandas as pd
from sklearn import preprocessing

In [7]:
iris = pd.read_csv("iris.csv")
df = pd.DataFrame(iris,columns=["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"])

In [8]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
iris.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [10]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [11]:
iris.shape

(150, 6)

In [12]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [13]:
iris.columns.values

array(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm',
       'PetalWidthCm', 'Species'], dtype=object)

In [14]:
iris['Species'].count()

np.int64(150)

In [15]:
iris.sort_index(axis=1, ascending=False)

,Species,SepalWidthCm,SepalLengthCm,PetalWidthCm,PetalLengthCm,Id
0,Iris-setosa,3.5,5.1,0.2,1.4,1
1,Iris-setosa,3.0,4.9,0.2,1.4,2
2,Iris-setosa,3.2,4.7,0.2,1.3,3
3,Iris-setosa,3.1,4.6,0.2,1.5,4
4,Iris-setosa,3.6,5.0,0.2,1.4,5
...,...,...,...,...,...,...
145,Iris-virginica,3.0,6.7,2.3,5.2,146
146,Iris-virginica,2.5,6.3,1.9,5.0,147
147,Iris-virginica,3.0,6.5,2.0,5.2,148
148,Iris-virginica,3.4,6.2,2.3,5.4,149
149,Iris-virginica,3.0,5.9,1.8,5.1,150

In [16]:
iris.iloc[5]

Id                         6
SepalLengthCm            5.4
SepalWidthCm             3.9
PetalLengthCm            1.7
PetalWidthCm             0.4
Species          Iris-setosa
Name: 5, dtype: object

In [17]:
iris[0:3]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [18]:
iris.iloc[:3,:5]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2

In [ ]:
iris.loc[:3,["SepalLengthCm","Species"]]

   SepalLengthCm      Species
0            5.1  Iris-setosa
1            4.9  Iris-setosa
2            4.7  Iris-setosa
3            4.6  Iris-setosa

In [20]:
iris.iloc[3:5, 0:2]

   Id  SepalLengthCm
3   4            4.6
4   5            5.0

In [21]:
iris['SepalLengthCm'].iloc[5]

np.float64(5.4)

In [22]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
dtype: int64

In [23]:
df.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [24]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
x=df[df.columns].values.astype(float)

In [26]:
min_max_scalar=preprocessing.MinMaxScaler()

In [27]:
x_scaled = min_max_scalar.fit_transform(x)

In [28]:
df_normalized = pd.DataFrame(x_scaled)

In [29]:
df_normalized

            0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [30]:
df['Species']=iris['Species']

In [31]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [32]:
label_encoder=preprocessing.LabelEncoder()

In [33]:
df['Species']=label_encoder.fit_transform(df['Species'])

In [34]:
df['Species'].unique()

array([0, 1, 2])

In [35]:
df['Species'].dtype

dtype('int64')

In [36]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [37]:
features_df=df.drop(columns=['Species'])

In [38]:
enc = preprocessing.OneHotEncoder()

In [39]:
enc_df=pd.DataFrame(enc.fit_transform(df[['Species']]).toarray())

In [40]:
df_encode = features_df.join(enc_df)

In [41]:
df_encode

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    0    1    2
0              5.1           3.5            1.4           0.2  1.0  0.0  0.0
1              4.9           3.0            1.4           0.2  1.0  0.0  0.0
2              4.7           3.2            1.3           0.2  1.0  0.0  0.0
3              4.6           3.1            1.5           0.2  1.0  0.0  0.0
4              5.0           3.6            1.4           0.2  1.0  0.0  0.0
..             ...           ...            ...           ...  ...  ...  ...
145            6.7           3.0            5.2           2.3  0.0  0.0  1.0
146            6.3           2.5            5.0           1.9  0.0  0.0  1.0
147            6.5           3.0            5.2           2.0  0.0  0.0  1.0
148            6.2           3.4            5.4           2.3  0.0  0.0  1.0
149            5.9           3.0            5.1           1.8  0.0  0.0  1.0

[150 rows x 7 columns]

In [42]:
df_encode.rename(columns={0:'Iris-Setosa',1:'Iris-Versicolar',2:'Iris-Verginica'},inplace=True)

In [43]:
df_encode

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Iris-Setosa,Iris-Versicolar,Iris-Verginica
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,0.0,0.0,1.0

In [44]:
one_hot_df = pd.get_dummies(df,prefix="Species",columns=['Species'],drop_first=False)

In [45]:
one_hot_df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_0,Species_1,Species_2
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

In [46]:
col = ['Species_0','Species_1', 'Species_2']
one_hot_df[col] = one_hot_df[col].astype(int)

In [47]:
one_hot_df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_0,Species_1,Species_2
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1